# Generated by Django 3.0.2 on 2020-02-15 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to='pics', verbose_name='Images'),
        ),
    ]
