# Generated by Django 3.0.2 on 2020-02-15 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_auto_20200215_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to='feedback/pics'),
        ),
    ]
