# Generated by Django 3.0.4 on 2020-03-26 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='RoomImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='VolumeRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('price', models.IntegerField(default=0)),
                ('capacity', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.CategoryRoom')),
                ('images', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.RoomImages')),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.VolumeRoom')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('comment', models.CharField(blank=True, max_length=170)),
                ('book_status', models.CharField(choices=[('Not_confirmed', 'Not_confirmed'), ('Confirmed', 'Confirmed'), ('Rejected', 'Rejected')], default='NF', max_length=13)),
                ('book_date', models.DateTimeField(auto_now_add=True)),
                ('book_pay_status', models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], default='UP', max_length=6)),
                ('has_child', models.BooleanField(blank=True, default=False)),
                ('clientName', models.CharField(max_length=64)),
                ('clientSurname', models.CharField(max_length=64)),
                ('clientEmail', models.EmailField(max_length=254)),
                ('clientPhone', models.IntegerField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Room')),
            ],
        ),
    ]
