# Generated by Django 2.2.8 on 2020-04-28 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='book_pay_status',
            field=models.ForeignKey(default='Неоплачено', on_delete=django.db.models.deletion.CASCADE, to='booking.BookPayStatus', verbose_name='Статус оплаты'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='book_status',
            field=models.ForeignKey(default='Online-В обработке', on_delete=django.db.models.deletion.CASCADE, to='booking.BookStatus', verbose_name='Статус брони'),
        ),
    ]
