# Generated by Django 3.0.4 on 2020-03-26 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20200327_0401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='market',
        ),
        migrations.RemoveField(
            model_name='match',
            name='sport',
        ),
        migrations.RemoveField(
            model_name='selection',
            name='market',
        ),
        migrations.DeleteModel(
            name='Market',
        ),
        migrations.DeleteModel(
            name='Match',
        ),
        migrations.DeleteModel(
            name='Selection',
        ),
        migrations.DeleteModel(
            name='Sport',
        ),
    ]
