# Generated by Django 3.0.4 on 2020-04-11 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20200411_1808'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'Бронь', 'verbose_name_plural': 'Брони'},
        ),
        migrations.AlterField(
            model_name='booking',
            name='book_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания брони'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='book_pay_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], default='UP', max_length=6, verbose_name='Статус оплаты'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='book_status',
            field=models.CharField(choices=[('Not_confirmed', 'Not_confirmed'), ('Confirmed', 'Confirmed'), ('Rejected', 'Rejected')], default='NF', max_length=13, verbose_name='Статус брони'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='clientEmail',
            field=models.EmailField(max_length=254, verbose_name='Email клиента'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='clientName',
            field=models.CharField(max_length=64, verbose_name='Имя клиента'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='clientPhone',
            field=models.IntegerField(verbose_name='Номер телефона клиента'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='clientSurname',
            field=models.CharField(max_length=64, verbose_name='Фамилия клиента'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='comment',
            field=models.CharField(blank=True, max_length=170, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date_from',
            field=models.DateField(verbose_name='Бронировать с'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date_to',
            field=models.DateField(verbose_name='Бронировать до'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='has_child',
            field=models.BooleanField(blank=True, default=False, verbose_name='Есть ли ребенок'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='booking.Room', verbose_name='Комната'),
        ),
    ]
