# Generated by Django 2.2.8 on 2020-04-17 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20200411_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Book Summary',
                'verbose_name_plural': 'Bookings Summary',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('booking.booking',),
        ),
        migrations.AddField(
            model_name='booking',
            name='totalsum',
            field=models.IntegerField(default=0, verbose_name='Полная стоимость'),
        ),
    ]
