# Generated by Django 3.0.4 on 2020-04-03 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20200327_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='images',
            field=models.ManyToManyField(blank=True, to='booking.RoomImages'),
        ),
    ]
