# Generated by Django 3.0.4 on 2020-04-08 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_auto_20200403_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.ManyToManyField(blank=True, to='booking.Room'),
        ),
    ]
