# Generated by Django 3.0.4 on 2020-04-09 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_auto_20200409_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.ManyToManyField(to='booking.Room'),
        ),
    ]
